In [11]:
import yfinance as yf
import numpy as np
import pandas as pd
import datetime

In [3]:
ticker = yf.Ticker("AAPL")
ticker_history = ticker.history(period='1d')
ticker_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-06-12 00:00:00-04:00,296.029999,297.140015,289.619995,291.130005,38742100,0.0,0.0

In [7]:
S = ticker_history["Close"].iloc[-1]
S

np.float64(291.1300048828125)

In [9]:
ticker.options

('2026-06-15',
 '2026-06-17',
 '2026-06-18',
 '2026-06-22',
 '2026-06-26',
 '2026-07-02',
 '2026-07-10',
 '2026-07-17',
 '2026-07-24',
 '2026-08-21',
 '2026-09-18',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [16]:
exp_date = datetime.datetime.strptime(ticker.options[-1], "%Y-%m-%d").date()
exp_date

datetime.date(2028, 12, 15)

In [22]:
opt_chain_call = ticker.option_chain(ticker.options[-1]).calls
opt_chain_call

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL281215C00005000,2026-06-09 14:45:42+00:00,5.0,288.00,284.00,289.0,0.0,0.000000,1.0,5,1.245121,True,REGULAR,USD
1,AAPL281215C00010000,2026-05-29 18:57:42+00:00,10.0,301.20,279.00,284.0,0.0,0.000000,25.0,25,0.988281,True,REGULAR,USD
2,AAPL281215C00015000,2026-05-29 18:52:36+00:00,15.0,295.25,274.00,279.0,0.0,0.000000,26.0,40,0.852541,True,REGULAR,USD
3,AAPL281215C00020000,2026-03-03 20:33:09+00:00,20.0,242.96,0.00,0.0,0.0,0.000000,NaN,0,0.000010,True,REGULAR,USD
4,AAPL281215C00025000,2026-03-03 20:31:48+00:00,25.0,239.26,0.00,0.0,0.0,0.000000,3.0,0,0.000010,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,AAPL281215C00560000,2026-06-10 17:25:06+00:00,560.0,8.23,7.25,8.8,0.0,0.000000,1.0,14,0.315375,False,REGULAR,USD
69,AAPL281215C00570000,2026-05-29 15:19:42+00:00,570.0,8.60,5.80,9.5,0.0,0.000000,1.0,6,0.327582,False,REGULAR,USD
70,AAPL281215C00580000,2026-06-11 16:47:21+00:00,580.0,7.00,5.60,7.7,0.0,0.000000,5.0,8,0.315452,False,REGULAR,USD
71,AAPL281215C00590000,2026-06-11 18:32:05+00:00,590.0,6.60,5.65,6.6,0.0,0.000000,1.0,102,0.308875,False,REGULAR,USD
72,AAPL281215C00600000,2026-06-12 19:55:06+00:00,600.0,5.60,5.30,6.7,-0.4,-6.666668,329.0,2403,0.315040,False,REGULAR,USD